#!/bin/bash
set -ex

ln -sf ~/dotfiles/zshrc ~/.zshrc
ln -sf ~/dotfiles/vimrc ~/.vimrc
ln -sf ~/dotfiles/gitconfig ~/.gitconfig

if ! [ $SPIN ]; then
  ln -s ~/dotfiles/gemrc ~/.gemrc
  ln -s ~/dotfiles/zshenv ~/.zshenv
  ln -s ~/dotfiles/zpreztorc ~/.zpreztorc
  ln -s ~/dotfiles/gitignore_global ~/.gitignore_global
fi
